### ISSUE TITLE
Почему именно так назвал?

### ISSUE THREAD

**Issue by sboriskin287** [AlekhinArt/myOrg#11]
https://github.com/AlekhinArt/myOrg/blob/5ff6f30572cede5adea3674912077678e872d26e/src/main/java/ru/egar/myOrg/organization/repository/OrganizationRepository.java#L12

**Comment by AlekhinArt** [comment]
Этим запросом достаем из бд список организаций, у которых в классе супортОрг поле  sendEmailBirthday true
т.е. другими словами, назвал его так, что бы не писать запрос ручками)
