### ISSUE TITLE
построй мапу orgId vs org и тогда тебе не надо будет делать каждый раз поиск. Просто бери по ключу w.getOrgId

### ISSUE THREAD

**Issue by sboriskin287** [AlekhinArt/myOrg#13]
https://github.com/AlekhinArt/myOrg/blob/5ff6f30572cede5adea3674912077678e872d26e/src/main/java/ru/egar/myOrg/scheduled/atnight/EveryNightBusiness.java#L37

**Comment by AlekhinArt** [comment]
исправлено
