### ISSUE TITLE
Зачем два воркер контроллера? в чем отличие от WorkerController?

### ISSUE THREAD

**Issue by sboriskin287** [AlekhinArt/myOrg#18]
https://github.com/AlekhinArt/myOrg/blob/5ff6f30572cede5adea3674912077678e872d26e/src/main/java/ru/egar/myOrg/worker/controller/WorkerControllerWeb.java#L26

**Comment by AlekhinArt** [comment]
По большому счету никакой разницы нет.
Сделано так было для удобства разделения данных идущих на фронт и данных приходящих с фронта, ничего не мешает объединить)
