### ISSUE TITLE
WokrkerShowDto и WorkerDto сделать одной дто, и через @JsonInclude(NON_NULL) управлять конечным json'ом для в response body

### ISSUE THREAD

**Issue by sboriskin287** [AlekhinArt/myOrg#19]
https://github.com/AlekhinArt/myOrg/blob/5ff6f30572cede5adea3674912077678e872d26e/src/main/java/ru/egar/myOrg/worker/dto/WorkerShowDto.java#L12

**Comment by AlekhinArt** [comment]
выполнено
