### ISSUE TITLE
Сделать не статичный метод и инжектить бин как и все остальные. Исправить здесь и везде

### ISSUE THREAD

**Issue by sboriskin287** [AlekhinArt/myOrg#2]
https://github.com/AlekhinArt/myOrg/blob/89f44ce51f8da5d50ea0bc7ac83e52a6bedc5ecf/src/main/java/ru/egar/myOrg/document/mapper/PassportMapper.java#L8C20-L8C20

**Comment by AlekhinArt** [comment]
Сделано
