### ISSUE TITLE
внутри пакета service сделать пакет impl и все имплементации переместить туда. Исправить здесь и везде

### ISSUE THREAD

**Issue by sboriskin287** [AlekhinArt/myOrg#3]
https://github.com/AlekhinArt/myOrg/blob/89f44ce51f8da5d50ea0bc7ac83e52a6bedc5ecf/src/main/java/ru/egar/myOrg/document/service/DocumentServiceImpl.java#L16

**Comment by AlekhinArt** [comment]
Сделано
