### ISSUE TITLE
Все реализацию перенести в метод run, ради одного вызова не стоит делать отдельный метод

### ISSUE THREAD

**Issue by sboriskin287** [AlekhinArt/myOrg#7]
https://github.com/AlekhinArt/myOrg/blob/89f44ce51f8da5d50ea0bc7ac83e52a6bedc5ecf/src/main/java/ru/egar/myOrg/scheduled/everyNight/EveryNightBusiness.java#L28

**Comment by AlekhinArt** [comment]
Сделано
